version: "3"

services:
  mysql-db:
    image: mysql:latest
    container_name: projects-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=eventsproject
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - mynetwork


  eventsproject-app:
    image: houssem69/foyerapp:1.0
    container_name: foyerapp
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/eventsproject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - mynetwork

 

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
